src/Entity/CategorieDeServices.php
<?php

namespace App\Entity;

use App\Repository\CategorieDeServicesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieDeServicesRepository::class)]
class CategorieDeServices
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: false)]
    private ?bool $EnAvant = false;

    #[ORM\Column(nullable: true)]
    private ?bool $Valide = null;

    #[ORM\OneToMany(mappedBy: 'categorieDeServices', targetEntity: Promotion::class)]
    private Collection $promotions;

    #[ORM\ManyToMany(targetEntity: Prestataire::class, mappedBy: 'CategorieDeServices')]
    private Collection $prestataires;

    public function __construct()
    {
       
        $this->promotions = new ArrayCollection();
        $this->prestataires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isEnAvant(): ?bool
    {
        return $this->EnAvant;
    }

    public function setEnAvant(?bool $EnAvant): static
    {
        $this->EnAvant = $EnAvant;

        return $this;
    }

    public function isValide(): ?bool
    {
        return $this->Valide;
    }

    public function setValide(?bool $Valide): static
    {
        $this->Valide = $Valide;

        return $this;
    }

    /**
     * @return Collection<int, Promotion>
     */
    public function getPromotions(): Collection
    {
        return $this->promotions;
    }

    public function addPromotion(Promotion $promotion): static
    {
        if (!$this->promotions->contains($promotion)) {
            $this->promotions->add($promotion);
            $promotion->setCategorieDeServices($this);
        }

        return $this;
    }

    public function removePromotion(Promotion $promotion): static
    {
        if ($this->promotions->removeElement($promotion)) {
            // set the owning side to null (unless already changed)
            if ($promotion->getCategorieDeServices() === $this) {
                $promotion->setCategorieDeServices(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Prestataire>
     */
    public function getPrestataires(): Collection
    {
        return $this->prestataires;
    }

    public function addPrestataire(Prestataire $prestataire): static
    {
        if (!$this->prestataires->contains($prestataire)) {
            $this->prestataires->add($prestataire);
            $prestataire->addCategorieDeService($this);
        }

        return $this;
    }

    public function removePrestataire(Prestataire $prestataire): static
    {
        if ($this->prestataires->removeElement($prestataire)) {
            $prestataire->removeCategorieDeService($this);
        }

        return $this;
    }
}

src/Controller/CategorieDeServicesController.php
<?php

namespace App\Controller;

use App\Entity\CategorieDeServices;
use App\Entity\Images;
use App\Entity\Prestataire;
use App\Entity\Promotion;
use App\Form\RechercheType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategorieDeServicesController extends AbstractController
{
    #[Route('/categorie/de/services/{id}', name: 'app_categorie_de_services')]
    public function index($id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(CategorieDeServices::class);
        $service = $repository->findOneBy(['id' => $id ]);
        $categorieDeServices =$repository->findAll();
        $repositoryImage = $entityManager->getRepository(Images::class);
        $image = $repositoryImage->findOneBy(['categorieDeServices'=>$id]);

        $repositoryPromotions = $entityManager->getRepository(Promotion::class); 
        $promotions = $repositoryPromotions->findBy(['categorieDeServices' =>$id]);

        
        

        $repositoryPrestataire = $entityManager->getRepository(Prestataire::class);
        $prestataires = $repositoryPrestataire->findByCategorieDeServicesId($id);

        
        
        $images = [];
        foreach ($prestataires as $prestataire) {
            
            $images[]= $repositoryImage->findOneBy(['prestataire' => $prestataire->getId()]);
        }
       
      

        $form = $this->createForm(RechercheType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $datas = $form->getData();

            return $this->redirectToRoute('resultSearch');
        } 

        $user = $this->getUser();

        $icone = '';
        if(!empty($user)){
           
            if($user->getRoles()[0]=="PRE"){
                $imageIcone = $entityManager->getRepository(Images::class)->findOneBy(['prestataire' => $user->getPrestataire()->getId() ]);
                
               
            }elseif($user->getRoles()[0]=="INT"){
                $imageIcone = $entityManager->getRepository(Images::class)->findOneBy(['internaute' => $user->getInternaute()->getId()]);
            }

            if($imageIcone == null){
                $icone = '';
            }else{
                $icone = $imageIcone->getImage();
            }
        }


       
        
        return $this->render('categorie_de_services/index.html.twig', [
            'controller_name' => 'CategorieDeServicesController',
            'categ' => $service, 
            'categorieDeServices' => $categorieDeServices,
            'image' => $image,
            'form' =>$form ->createView(),
            'prestataires' => $prestataires,
            'images' => $images,
            'icone' => $icone,
            'promotions' => $promotions,
        ]);
    }
}

templates/categorie_de_services/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ categ.nom }}{% endblock %}

{% block body %}

<div class="container_main">
    <div class="main">
        
        <div class="container_categorieDeServices" id="sidebar">
            <h2>Categories de services</h2>
            <ul class="categorieDeServices_list">
                {% for service in categorieDeServices %}
                {% if service.valide %}
                    <li class='button'><a href="{{path('app_categorie_de_services', {'id': service.id})}}">{{ service.nom }}</a></li>
                {% endif %}
                {% endfor %}           
            </ul>
        </div>
        <div class="container_recherche">
         {% include 'block/recherche.twig' %}
        </div>
        <div class="container_card_categorieDeServices">
            <div class="card" >
                <img src="{{asset(image.image)}}" class="card-img-top" alt="{{image.id}}">
                <div class="card-body">
                    <h5 class="card-title">{{ categ.nom}}</h5>
                    <p class="card-text">{{ categ.description}}</p>
                </div>
               
            </div> 
        </div>
        <div class="container_prestataires">
            <div class="row">
                {% for prestataire in prestataires %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            {% for image in images %}
                                {% if image is not null and image.prestataire.id == prestataire.id %}
                                    <img src="{{asset(image.image)}}" class="card-img-top" alt="{{ image.prestataire.id }}">
                                {% endif %}
                            {% endfor %}
                            <div class="card-body">
                                <h5 class="card-title">{{ prestataire.nom }}</h5>
                                <p class="card-text">Site Internet: {{ prestataire.siteInternet }}</p>
                                <p class="card-text">Numéro de téléphone: {{ prestataire.numTel }}</p>
                                <p class="card-text">Numéro de TVA: {{ prestataire.numTva }}</p>
                                
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container_promotions">
            <div class="container_promo">
                <h3>Profitez de nos promotions </h3>
                {% for promotion in promotions %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{promotion.nom}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{promotion.categorieDeServices.nom}}</h6>
                        <p class="card-text">{{promotion.description}}</p>
                    <h6 class="card-subtitle mb-2 text-muted">Du {{ promotion.debut|date('d-m-Y') }} au {{ promotion.fin|date('d-m-Y') }}</h6>
                        <a href="#" class="card-link">Télécharger</a>
                    </div>
                </div>
                {% endfor %}  
            
            </div>
        </div>
    </div>
</div>

{% endblock %}